[workspace]
members = ["evaluator", "lexer", "parser", "repl", "vmachine"]

[workspace.dependencies]
error-stack = {path = "/Users/jaredmoulton/Developer/hash/main/packages/libs/error-stack/"}
owo-colors = {version = "3.5.0", features = ["supports-colors"]}
expect-test = "1.4.0"
