[package]
name = "interpreter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_matches = "1.5.0"
error-stack = "0.1.1"
pretty_assertions = "1.3.0"
