edition = "2021"
unstable_features = true
version = "Two"

format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
struct_lit_width = 35
struct_variant_width = 70
imports_granularity = "Crate"
format_macro_bodies = true
format_macro_matchers = true
where_single_line = true
imports_layout = "HorizontalVertical"
fn_args_layout = "Compressed"
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
