#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OpCode {
    Const(usize),
    JumpNotTruthy(usize),
    Jump(usize),
    CreateGlobal,
    SetGlobal(usize),
    GetGlobal(usize),
    Call,
    Add,
    Sub,
    Mul,
    Div,
    Neg,
    Positive,
    Equal,
    NotEqual,
    GreaterThan,
    LessThan,
    Bang,
    Pop,
    Print,
    NoOp,
}
